### ISSUE TITLE
❌ Invalid Links on README.MD

### ISSUE THREAD

**Issue by noejunior299** [LUK3D/uxf-cli#1]
The path of the links to UXFlutter in README.md are wrong, they redirect to https://uxflatter.com instead of redirecting to https://uxflutter.com/, I hope they fix it, the project tends to be promising man.

**Comment by LUK3D** [comment]
Thanks for reporting. 
Just published version 1.1.2 and this should be fixed.

**Comment by noejunior299** [comment]
Good, keep up the great work and I'll keep using and contributing to uxflutter ✨.
